### ISSUE TITLE
distill_training error

### ISSUE THREAD

**Issue by youngwanLEE** [segmind/distill-sd#10]
Hi,

When I ran the distill_training by following your [command](https://github.com/segmind/distill-sd#training-the-model), I encountered this error.

> Traceback (most recent call last):                                                                                                                                                                                                   [73/1822]
  File "/home/user/sdm-kd/distill_training.py", line 1199, in <module>
    main()
  File "/home/user/sdm-kd/distill_training.py", line 999, in main
    cast_hook(unet,KD_student,args.distill_level,False)
  File "/home/user/sdm-kd/distill_training.py", line 992, in cast_hook
    unet.down_blocks[i].register_forward_hook(getActivation(dicts,'d'+str(i),True))
  File "/home/user/anaconda3/envs/uvit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'down_blocks'

Could you check this? 

Thanks in advance.

**Comment by Gothos** [comment]
I'll have a look at it, thanks for pointing the issue out!

**Comment by DragonDRLI** [comment]
Hi, @youngwanLEE @Gothos You can try replacing unet.down_blocks with unet.module.down_blocks.

**Comment by Gothos** [comment]
Ah. Have the diffusers module layouts changed? That would explain the issue.

**Comment by shreyas269** [comment]
Replacing `unet.<blocks>` with `accelerator.unwrap_model(unet).<blocks>` does it. It unwraps the model from the additional layer added by accelerator.prepare
